### ISSUE TITLE
Moving repository

### ISSUE THREAD

**Issue by mschubert** [mschubert/ebits#91]
I'm planning to move this repository to my personal account because there hasn't been much activity here, and the latter is over 600 commits ahead of `EBI-predocs/master`.

If there is any reason why I shouldn't please let me know, otherwise I'll go ahead a week from now.

Please note that old links will still resolve via an `HTTP/302`.

/cc @klmr @mattjeffryes

**Comment by klmr** [comment]
✅ from me.

**Comment by mschubert** [comment]
Move completed

Predocs branches are still available at:

https://github.com/mschubert/ebits/tree/master_predocs
https://github.com/mschubert/ebits/tree/develop_predocs

**Comment by barzine** [comment]
Late to the party
Can you maybe forked it to the ebi-predoc group though?
This is particularly useful and I am afraid that new generations will missed it.

**Comment by mschubert** [comment]
Hi Mitra,
What do you think would be the most useful here for them?
There's quite a bit of legacy code and I've split out `clustermq` and `narray` as packages, so maybe a "useful R packages" collection would make more sense there?

**Comment by barzine** [comment]
Yes, totally.
I was wondering myself if creating a 'useful packages and tools' (R or other) repo would not be the best.
